"""uuid 2

Revision ID: 08da76725c1a
Revises: b0cbef475762
Create Date: 2023-04-15 15:44:11.079130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08da76725c1a'
down_revision = 'b0cbef475762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
