"""uuid 1

Revision ID: b0cbef475762
Revises: 3ab36326c016
Create Date: 2023-04-15 15:41:00.275929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cbef475762'
down_revision = '3ab36326c016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
