"""uuid 5

Revision ID: dfa2fed24859
Revises: 34e24c5d70e9
Create Date: 2023-04-15 18:57:41.200860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa2fed24859'
down_revision = '34e24c5d70e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
